<template>
    <div class="block">
        Lorem ipsum, dolor <span class="text-color-1">sit amet consectetur adipisicing elit. Doloremque</span> <span class="text-color-2">commodi corporis consequuntur placeat, suscipit repudiandae,</span> quo aut expedita alias harum quidem vel qui optio nobis explicabo mollitia in error! Quidem. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis adipisci aliquid laudantium modi quae provident odit voluptatem temporibus iusto fugit! Sequi exercitationem nostrum ex minima, at architecto tempore aut asperiores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat esse, perspiciatis aliquam aliquid ipsam qui in autem sapiente repellendus magni a accusamus, architecto possimus expedita praesentium rem perferendis ad dolorem!
        <br>
        <br>
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. <span class="text-color-2">Doloremque commodi corporis consequuntur placeat, suscipit repudiandae, quo aut expedita alias </span>harum quidem vel qui optio nobis explicabo mollitia in error! Quidem. Lorem, ipsum dolor sit amet consectetur adipisicing elit. <span class="text-color-1">Veritatis</span> adipisci aliquid laudantium modi quae provident odit voluptatem temporibus iusto fugit! Sequi exercitationem nostrum ex minima, at architecto tempore aut asperiores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat esse, perspiciatis aliquam aliquid ipsam qui in autem sapiente repellendus magni a accusamus, architecto possimus expedita praesentium rem perferendis ad dolorem!
        <br>
        <br>
        Lorem ipsum, dolor <span class="text-color-1">sit amet consectetur adipisicing elit.</span> Doloremque commodi corporis consequuntur placeat, suscipit repudiandae, quo aut expedita alias harum quidem vel qui optio nobis explicabo mollitia in error! Quidem. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis adipisci aliquid laudantium modi quae provident odit voluptatem temporibus iusto fugit! Sequi exercitationem nostrum ex minima, at architecto tempore aut asperiores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat esse, perspiciatis aliquam aliquid ipsam qui in autem sapiente repellendus magni a accusamus, architecto possimus expedita praesentium rem perferendis ad dolorem!
        <br>
        <br>
        Lorem ipsum, dolor sit amet consectetur <span class="text-color-2">adipisicing elit. Doloremque commodi corporis consequuntur placeat, suscipit repudiandae, </span>quo aut expedita alias harum quidem vel qui optio nobis explicabo mollitia in error! Quidem. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis adipisci aliquid laudantium modi quae provident odit voluptatem temporibus iusto fugit! Sequi exercitationem nostrum ex minima, at architecto tempore aut asperiores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat esse, perspiciatis aliquam aliquid ipsam qui in autem sapiente repellendus magni a accusamus, architecto possimus expedita praesentium rem perferendis ad dolorem!
        <span class="text-color-1">Lorem ipsum,</span> dolor sit amet consectetur adipisicing elit. Doloremque commodi corporis consequuntur placeat, suscipit repudiandae, quo aut expedita alias harum quidem vel qui optio nobis explicabo mollitia in error! Quidem. Lorem, <span class="text-color-1">ipsum dolor sit amet</span> consectetur adipisicing elit. Veritatis adipisci aliquid laudantium modi quae provident odit voluptatem temporibus iusto fugit! Sequi exercitationem nostrum ex minima, at architecto tempore aut asperiores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat esse, perspiciatis aliquam aliquid ipsam qui in autem sapiente repellendus magni a accusamus, architecto possimus expedita praesentium rem perferendis ad dolorem!
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Doloremque commodi <span class="text-color-2">corporis consequuntur placeat, suscipit repudiandae, quo aut expedita </span>alias harum quidem vel qui optio nobis explicabo mollitia in error! Quidem. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis adipisci aliquid laudantium modi quae provident odit voluptatem temporibus iusto fugit! Sequi exercitationem nostrum ex minima, at architecto tempore aut asperiores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat esse, perspiciatis aliquam aliquid ipsam qui in autem sapiente repellendus magni a accusamus, architecto possimus expedita praesentium rem perferendis ad dolorem!
        <br>
        <br>
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Doloremque commodi corporis consequuntur <span class="text-color-1">placeat,</span> suscipit repudiandae, quo aut expedita alias harum quidem vel qui optio nobis explicabo mollitia in error! Quidem. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis adipisci aliquid laudantium modi quae provident odit voluptatem temporibus iusto fugit! Sequi exercitationem nostrum ex minima, at architecto tempore aut asperiores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat esse, perspiciatis aliquam aliquid ipsam qui in autem sapiente repellendus magni a accusamus, architecto possimus expedita praesentium rem perferendis ad dolorem!
        Lorem ipsum, <span class="text-color-1">dolor sit amet consectetur adipisicing elit. Doloremque commodi corporis consequuntur placeat</span>, suscipit repudiandae, quo aut expedita alias harum quidem vel qui optio nobis explicabo mollitia in error! Quidem. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis adipisci aliquid laudantium modi quae provident odit voluptatem temporibus iusto fugit! Sequi exercitationem nostrum ex minima, at architecto tempore aut asperiores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat esse, perspiciatis aliquam aliquid ipsam qui in autem sapiente repellendus magni a accusamus, architecto possimus expedita praesentium rem perferendis ad dolorem!
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Doloremque commodi corporis consequuntur placeat, suscipit repudiandae, quo aut expedita alias harum quidem vel qui optio nobis explicabo mollitia in error! Quidem. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis adipisci aliquid laudantium modi quae provident odit voluptatem temporibus iusto fugit! Sequi exercitationem nostrum ex minima, at architecto tempore aut asperiores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat esse, perspiciatis aliquam aliquid ipsam qui in autem sapiente repellendus magni a accusamus, architecto possimus expedita praesentium rem perferendis ad dolorem!
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Doloremque commodi corporis consequuntur placeat, suscipit repudiandae, quo aut expedita alias harum quidem vel qui optio nobis explicabo mollitia in error! Quidem. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis adipisci aliquid laudantium modi quae provident odit voluptatem temporibus iusto fugit! Sequi exercitationem nostrum ex minima, at architecto tempore aut asperiores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat esse, perspiciatis aliquam aliquid ipsam qui in autem sapiente repellendus magni a accusamus, architecto possimus expedita praesentium rem perferendis ad dolorem!
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Doloremque commodi corporis consequuntur placeat, suscipit repudiandae, quo aut expedita alias harum quidem vel qui optio nobis explicabo mollitia in error! Quidem. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis adipisci aliquid laudantium modi quae provident odit voluptatem temporibus iusto fugit! Sequi exercitationem nostrum ex minima, at architecto tempore aut asperiores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat esse, perspiciatis aliquam aliquid ipsam qui in autem sapiente repellendus magni a accusamus, architecto possimus expedita praesentium rem perferendis ad dolorem!
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Doloremque commodi corporis consequuntur placeat, suscipit repudiandae, quo aut expedita alias harum quidem vel qui optio nobis explicabo mollitia in error! Quidem. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis adipisci aliquid laudantium modi quae provident odit voluptatem temporibus iusto fugit! Sequi exercitationem nostrum ex minima, at architecto tempore aut asperiores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat esse, perspiciatis aliquam aliquid ipsam qui in autem sapiente repellendus magni a accusamus, architecto possimus expedita praesentium rem perferendis ad dolorem!
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Doloremque commodi corporis consequuntur placeat, suscipit repudiandae, quo aut expedita alias harum quidem vel qui optio nobis explicabo mollitia in error! Quidem. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis adipisci aliquid laudantium modi quae provident odit voluptatem temporibus iusto fugit! Sequi exercitationem nostrum ex minima, at architecto tempore aut asperiores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat esse, perspiciatis aliquam aliquid ipsam qui in autem sapiente repellendus magni a accusamus, architecto possimus expedita praesentium rem perferendis ad dolorem!
        Lorem ipsum, dolor sit <span class="text-color-1">amet consectetur</span> adipisicing elit. Doloremque commodi corporis consequuntur placeat, suscipit repudiandae, quo aut expedita alias harum quidem vel qui optio nobis explicabo mollitia in error! Quidem. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis adipisci aliquid laudantium modi quae provident odit voluptatem temporibus iusto fugit! Sequi exercitationem nostrum ex minima, at architecto tempore aut asperiores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat esse, perspiciatis aliquam aliquid ipsam qui in autem sapiente repellendus magni a accusamus, architecto possimus expedita praesentium rem perferendis ad dolorem!
        <br><br>
        <span class="text-color-1">Lorem ipsum, dolor sit amet consectetur adipisicing elit.</span> Doloremque commodi corporis consequuntur placeat, suscipit repudiandae, quo aut expedita alias harum quidem vel qui optio nobis explicabo mollitia in error! Quidem. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis adipisci aliquid laudantium modi quae provident odit voluptatem temporibus iusto fugit! Sequi exercitationem nostrum ex minima, at architecto tempore aut asperiores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat esse, perspiciatis aliquam aliquid ipsam qui in autem sapiente repellendus magni a accusamus, architecto possimus expedita praesentium rem perferendis ad dolorem!
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Doloremque commodi corporis consequuntur placeat, suscipit repudiandae, quo aut expedita alias harum quidem vel qui optio nobis explicabo mollitia in error! Quidem. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis adipisci aliquid laudantium modi quae provident odit voluptatem temporibus iusto fugit! Sequi exercitationem nostrum ex minima, at architecto tempore aut asperiores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat esse, perspiciatis aliquam aliquid ipsam qui in autem sapiente repellendus magni a accusamus, architecto possimus expedita praesentium rem perferendis ad dolorem!
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Doloremque commodi corporis consequuntur placeat, suscipit repudiandae, quo aut expedita alias harum quidem vel qui optio nobis explicabo mollitia in error! Quidem. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis adipisci aliquid laudantium modi quae provident odit voluptatem temporibus iusto fugit! Sequi exercitationem nostrum ex minima, at architecto tempore aut asperiores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat esse, perspiciatis aliquam aliquid ipsam qui in autem sapiente repellendus magni a accusamus, architecto possimus expedita praesentium rem perferendis ad dolorem!
        
        <br>
        <br>
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Doloremque commodi corporis consequuntur placeat, suscipit repudiandae, quo aut expedita alias harum quidem vel qui optio nobis explicabo mollitia in error! Quidem. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis adipisci aliquid laudantium modi quae provident odit voluptatem temporibus iusto fugit! Sequi exercitationem nostrum ex minima, at architecto tempore aut asperiores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat esse, perspiciatis aliquam aliquid ipsam qui in autem sapiente repellendus magni a accusamus, architecto possimus expedita praesentium rem perferendis ad dolorem!
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Doloremque commodi corporis consequuntur placeat, suscipit repudiandae, quo aut expedita alias harum quidem vel qui optio nobis explicabo mollitia in error! Quidem. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis adipisci aliquid laudantium modi quae provident odit voluptatem temporibus iusto fugit! Sequi exercitationem nostrum ex minima, at architecto tempore aut asperiores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat esse, perspiciatis aliquam aliquid ipsam qui in autem sapiente repellendus magni a accusamus, architecto possimus expedita praesentium rem perferendis ad dolorem!
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Doloremque commodi corporis consequuntur placeat, suscipit repudiandae, quo aut expedita alias harum quidem vel qui optio nobis explicabo mollitia in error! Quidem. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis adipisci aliquid laudantium modi quae provident odit voluptatem temporibus iusto fugit! Sequi exercitationem nostrum ex minima, at architecto tempore aut asperiores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat esse, perspiciatis aliquam aliquid ipsam qui in autem sapiente repellendus magni a accusamus, architecto possimus expedita praesentium rem perferendis ad dolorem!

    </div>
</template>

<script>

</script>

<style scoped>
.block {
  max-width: 1000px;
  margin-top: 80px;
  text-align: justify;
  overflow-wrap: break-word;
  hyphens: auto;
}
</style>